spring.application.name=inventory-service

server.port=8083

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

# Topics
spring.kafka.template.saga-topic=saga-events
spring.kafka.template.inventory-process-topic=inventory-events
spring.kafka.template.compensation-process-topic=compensation-events