package org.project.common.saga;

public enum SagaStatus {
    ORDER_INITIATED,
    ORDER_CANCELED,
    ORDER_COMPLETED,

    PAYMENT_INITIATED,
    PAYMENT_FAILED,
    PAYMENT_COMPLETED,

    INVENTORY_RESERVATION_INITIATED,
    INVENTORY_RESERVED,
    INVENTORY_UPDATED,
    INVENTORY_CANCELED,

    SAGA_COMPLETED,
    SAGA_FAILED
}